# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(help_text='The day number of this game')),
                ('weather', models.CharField(choices=[('good', 'Good'), ('snow', 'Snow')], help_text='The autocalculated weather for the day', max_length=10)),
                ('elves_woods', models.PositiveIntegerField(help_text='Elves sent to the woods by the player')),
                ('elves_forest', models.PositiveIntegerField(help_text='Elves sent to the forest by the player')),
                ('elves_mountain', models.PositiveIntegerField(help_text='Elves sent to the mountains by the player')),
            ],
            options={
                'get_latest_by': 'day',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('elves_start', models.PositiveIntegerField(default=12)),
                ('player_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='game.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together=set([('session', 'day')]),
        ),
    ]
