# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='elves_mountain',
            new_name='elves_mountains',
        ),
    ]
