# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20171118_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.PositiveIntegerField(help_text='The current day.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='elves_forest',
            field=models.PositiveIntegerField(help_text='Elves sent to the forest by the player. These elves acquire £20 worth of wood for this day if the weather was good. If not, they will return empty-handed.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='elves_mountains',
            field=models.PositiveIntegerField(help_text='Elves sent to the mountains by the player. These elves acquire £50 worth of wood for this day if the weather was good. If not, they will all die.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='elves_woods',
            field=models.PositiveIntegerField(help_text='Elves sent to the woods by the player. These elves acquire £10 worth of wood for this day.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='session',
            field=models.ForeignKey(help_text='The session for the day.', on_delete=django.db.models.deletion.CASCADE, related_name='days', to='game.Session'),
        ),
        migrations.AlterField(
            model_name='day',
            name='weather',
            field=models.CharField(choices=[('good', 'Good'), ('snow', 'Snow')], help_text='The autocalculated weather for the day. If the weather is good, all elves will return. If it snowed, all elves sent to the mountains will die and any elves sent to the forest return empty-handed.', max_length=10),
        ),
    ]
